### ISSUE TITLE
Project Export Error

### ISSUE THREAD

**Issue by avn3r** [Labelbox/labelspark#30]
Hello, I'm getting errors when trying to export a project into Databricks.

I tried both Databricks 9.1 and 10.3 LTS, but they both give the same error.
`lb_df = labelspark.get_annotations(client, "cl157rvtk0zxy0z7c1p7q7puy", spark, sc)`

I managed to get other projects to export properly, but this particular project has about 50k annotated images and over 200k bbox annotations. I imported the annotations via Python SDK and confirmed annotating work as expected on the Labelbox UI but databricks export is not working for this project.

Error Message:
```
Py4JJavaError                             Traceback (most recent call last)
<[command-1481209477824276]()> in <module>
----> 1 lb_df = labelspark.get_annotations(client, "cl157rvtk0zxy0z7c1p7q7puy", spark, sc)

/databricks/python/lib/python3.8/site-packages/labelspark/__init__.py in get_annotations(client, project_id, spark, sc)
     49     with urllib.request.urlopen(project.export_labels()) as url:
     50         api_response_string = url.read().decode()  # this is a string of JSONs
---> 51     bronze_table = jsonToDataFrame(api_response_string, spark, sc)
     52     bronze_table = dataframe_schema_enrichment(bronze_table)
     53     return bronze_table

/databricks/python/lib/python3.8/site-packages/labelspark/__init__.py in jsonToDataFrame(json, spark, sc, schema)
    195     if schema:
    196         reader.schema(schema)
--> 197     return reader.json(sc.parallelize([json]))
    198 
    199 

/databricks/spark/python/pyspark/sql/readwriter.py in json(self, path, schema, primitivesAsString, prefersDecimal, allowComments, allowUnquotedFieldNames, allowSingleQuotes, allowNumericLeadingZero, allowBackslashEscapingAnyCharacter, mode, columnNameOfCorruptRecord, dateFormat, timestampFormat, multiLine, allowUnquotedControlChars, lineSep, samplingRatio, dropFieldIfAllNull, encoding, locale, pathGlobFilter, recursiveFileLookup, allowNonNumericNumbers, modifiedBefore, modifiedAfter)
    382             keyed._bypass_serializer = True
    383             jrdd = keyed._jrdd.map(self._spark._jvm.BytesToString())
--> 384             return self._df(self._jreader.json(jrdd))
    385         else:
    386             raise TypeError("path can be only string, list or RDD")

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    115     def deco(*a, **kw):
    116         try:
--> 117             return f(*a, **kw)
    118         except py4j.protocol.Py4JJavaError as e:
    119             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o1781.json.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 15 in stage 3.0 failed 4 times, most recent failure: Lost task 15.3 in stage 3.0 (TID 20) (10.48.85.196 executor 1): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2828)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2775)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2769)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2769)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1305)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1305)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1305)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3036)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2977)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2965)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1067)
	at org.apache.spark.SparkContext.runJobInternal(SparkContext.scala:2477)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2460)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2572)
	at org.apache.spark.sql.catalyst.json.JsonInferSchema.infer(JsonInferSchema.scala:94)
	at org.apache.spark.sql.execution.datasources.json.TextInputJsonDataSource$.$anonfun$inferFromDataset$1(JsonDataSource.scala:110)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:273)
	at org.apache.spark.sql.execution.datasources.json.TextInputJsonDataSource$.inferFromDataset(JsonDataSource.scala:110)
	at org.apache.spark.sql.DataFrameReader.$anonfun$json$1(DataFrameReader.scala:693)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:693)
	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:673)
	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:656)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by nickaustinlee** [comment]
I wonder if the size of the export and the transformations which are occurring here are crashing the driver in some way. Could you see if you get the same error on a significantly larger driver? I searched the web for similar errors, and they all seem to relate to memory. Since you are using a dataset with more annotations, this might be pushing the driver over. 

We'll also take a look at the get_annotations method to figure out how we can be more memory-safe with the export. Right now we're storing the entire JSON string in memory, which poses some risks when the JSON is very large. We didn't assume we had permission to write the JSON file to disk, but for larger projects this may be necessary. 

One near-term workaround you could use is to use the standard Labelbox SDK to export your JSON string to a local .json file written to disk, and then use Spark to read the file. Once it's loaded, you can call the next method to convert it into the expected "Bronze table" which will work with other methods in LabelSpark: 

    bronze_table = jsonToDataFrame(api_response_string, spark, sc) <-- memory limits probably crashing the driver here
    bronze_table = dataframe_schema_enrichment(bronze_table)

As you can see, jsonToDataFrame is written to take in the JSON string (which is probably so big it's crashing memory). If it is modified to accept a file path and you write your JSON to disk, that might work. 

> def jsonToDataFrame(json, spark, sc, schema=None):
>     # code taken from Databricks tutorial https://docs.azuredatabricks.net/_static/notebooks/transform-complex-data-types-python.html
>     reader = spark.read
>     if schema:
>         reader.schema(schema)
>     return reader.json(sc.parallelize([json]))

Thank you for reporting the issue. We'll look to fix this in future releases.
